import { Fn, abs, clamp, float, floor, fract, length, max, min, mix, mod, smoothstep, step, vec2, vec3 } from 'three/tsl';
import { authoredColor } from '../color-tsl.js';
import { Surface } from './surface.js';
import { cracks, fbm01, fbm3, fbm4, fbm5, hash11, hash12, hash42, shear, shearPeriod, warp as domainWarp, worley } from '../noise-tsl.js';

// CONCRETE: authored channel stack migrated from surfaces-arch.js.
export const concreteSurface = Fn(([coords, seed, , , param]) => {
  const alb = vec3(0.5).toVar(), h = float(0.5).toVar();
  const rough = float(0.5).toVar(), metal = float(0).toVar(), ao = float(1).toVar();
  const P = vec2(float(8.0)).toVar();
  const p = ((coords).mul(P)).add((seed).mul(float(13.7))).toVar();
  const macro = fbm01(fbm4((p).mul(float(0.5)), (P).mul(float(0.5)), float(0.58))).toVar();
  const mid = fbm01(fbm5(domainWarp((p).mul(float(2.0)), (P).mul(float(2.0)), float(0.7), 3), (P).mul(float(2.0)), float(0.5))).toVar();
  const fine = fbm01(fbm4((p).mul(float(18.0)), (P).mul(float(18.0)), float(0.5))).toVar();
  const micro = fbm01(fbm3((p).mul(float(26.0)), (P).mul(float(26.0)), float(0.5))).toVar();
  const cLight = authoredColor(0.520, 0.512, 0.492).toVar();
  const cMid = authoredColor(0.395, 0.392, 0.385).toVar();
  const cDark = authoredColor(0.255, 0.253, 0.258).toVar();
  const c = mix(cMid, cLight, smoothstep(float(0.35), float(0.85), macro)).toVar();
  c.assign(mix(c, cDark, (smoothstep(float(0.55), float(0.95), mid)).mul(float(0.55))));
  c.mulAssign((float(0.93)).add((float(0.14)).mul(fine)));
  const pourB = fbm01(fbm4(domainWarp(((p).mul(float(1.5))).add(float(8.3)), (P).mul(float(1.5)), float(0.6), 3), (P).mul(float(1.5)), float(0.58))).toVar();
  pourB.assign(clamp((((pourB).sub(float(0.5))).mul(float(2.5))).add(float(0.5)), float(0.0), float(1.0)));
  c.mulAssign((float(0.82)).add((float(0.38)).mul(pourB)));
  const wash = fbm01(fbm4(((p).mul(float(7.0))).add(float(2.0)), (P).mul(float(7.0)), float(0.5))).toVar();
  wash.assign(clamp((((wash).sub(float(0.5))).mul(float(2.2))).add(float(0.5)), float(0.0), float(1.0)));
  c.mulAssign((float(0.925)).add((float(0.155)).mul(wash)));
  h.assign(((float(0.62)).add(((fine).sub(float(0.5))).mul(float(0.035)))).add(((mid).sub(float(0.5))).mul(float(0.05))));
  rough.assign(((float(0.70)).add(((mid).sub(float(0.5))).mul(float(0.16)))).add(((micro).sub(float(0.5))).mul(float(0.07))));
  ao.assign(float(1.0));
  metal.assign(float(0.0));
  const agg = worley((p).mul(float(13.0)), (P).mul(float(13.0)), float(0.95)).toVar();
  const aggShape = smoothstep(float(0.10), float(0.46), agg.x).oneMinus().toVar();
  const aggRnd = agg.z.toVar();
  const aggExposed = (aggShape).mul(step(float(0.74), (fbm01(fbm3(((p).mul(float(3.0))).add(float(5.0)), (P).mul(float(3.0)), float(0.5)))).add((aggRnd).mul(float(0.35))))).toVar();
  h.addAssign(((aggExposed).mul(float(0.022))).mul((float(0.5)).add(aggRnd)));
  c.assign(mix(c, mix(authoredColor(0.335, 0.320, 0.300), authoredColor(0.560, 0.545, 0.505), aggRnd), (aggExposed).mul(float(0.7))));
  rough.addAssign(((aggExposed).mul(float(0.07))).mul((aggRnd).sub(float(0.5))));
  const sand = worley((p).mul(float(20.0)), (P).mul(float(20.0)), float(1.0)).toVar();
  const sandM = smoothstep(float(0.05), float(0.44), sand.x).oneMinus().toVar();
  const sandSel = (float(0.40)).add((float(0.60)).mul(step(float(0.30), sand.z))).toVar();
  h.addAssign(((sandM).mul(sandSel)).mul(float(0.028)));
  c.mulAssign((float(1.0)).add((((sandM).mul(sandSel)).sub(float(0.20))).mul(float(0.15))));
  rough.addAssign((((sand.z).sub(float(0.5))).mul(float(0.11))).add((sandM).mul(float(0.04))));
  ao.subAssign((sandM).mul(float(0.06)));
  const sandTrough = smoothstep(float(0.52), float(0.88), sand.x).toVar();
  c.assign(mix(c, (c).mul(float(0.86)), (sandTrough).mul(float(0.34))));
  const pores = worley((p).mul(float(22.0)), (P).mul(float(22.0)), float(1.0)).toVar();
  const pore = (smoothstep(float(0.0), float(0.26), pores.x).oneMinus()).mul(step(float(0.84), pores.w)).toVar();
  h.subAssign((pore).mul(float(0.055)));
  ao.subAssign((pore).mul(float(0.55)));
  rough.addAssign((pore).mul(float(0.10)));
  const formAmt = param.x.toVar();
  const jointAmt = param.y.toVar();
  const boards = (coords.y).mul(float(4.0)).toVar();
  const bi = floor(boards).toVar();
  const bf = fract(boards).toVar();
  const seam = ((float(1.0)).sub(smoothstep(float(0.0), float(0.030), bf))).add((float(1.0)).sub(smoothstep(float(0.0), float(0.030), (float(1.0)).sub(bf)))).toVar();
  seam.assign(clamp(seam, float(0.0), float(1.0)));
  const boardStep = (((hash11((bi).add(seed))).sub(float(0.5))).mul(float(0.028))).mul(formAmt).toVar();
  h.addAssign(boardStep);
  h.subAssign(((seam).mul(float(0.055))).mul(formAmt));
  ao.subAssign(((seam).mul(float(0.40))).mul(formAmt));
  c.mulAssign((float(1.0)).sub(((seam).mul(float(0.16))).mul(formAmt)));
  const bleed = (((float(1.0)).sub(smoothstep(float(0.0), float(0.10), abs((bf).sub(float(0.02)))))).mul(float(0.5))).mul(formAmt).toVar();
  c.assign(mix(c, (cLight).mul(float(1.05)), ((bleed).mul(float(0.35))).mul(fbm01(fbm3((p).mul(float(8.0)), (P).mul(float(8.0)), float(0.5))))));
  const tf = (fract(vec2((coords.x).mul(float(3.0)), (boards).mul(float(0.5))))).sub(float(0.5)).toVar();
  const tieRnd = hash12((floor(vec2((coords.x).mul(float(3.0)), (boards).mul(float(0.5))))).add(seed)).toVar();
  const tie = ((smoothstep(float(0.05), float(0.085), length((tf).mul(vec2(float(1.0), float(2.0))))).oneMinus()).mul(step(float(0.45), tieRnd))).mul(formAmt).toVar();
  h.subAssign((tie).mul(float(0.10)));
  ao.subAssign((tie).mul(float(0.5)));
  c.assign(mix(c, (cDark).mul(float(0.85)), (tie).mul(float(0.6))));
  const jd = abs((fract((coords).add(float(0.5)))).sub(float(0.5))).toVar();
  const joint = max((float(1.0)).sub(smoothstep(float(0.0035), float(0.010), jd.x)), (float(1.0)).sub(smoothstep(float(0.0035), float(0.010), jd.y))).toVar();
  joint.mulAssign(jointAmt);
  h.subAssign((joint).mul(float(0.10)));
  ao.subAssign((joint).mul(float(0.55)));
  c.assign(mix(c, (cDark).mul(float(0.62)), (joint).mul(float(0.65))));
  const swirl = fbm01(fbm3(domainWarp(((p).mul(float(1.1))).add(float(3.0)), (P).mul(float(1.1)), float(1.4), 3), (P).mul(float(1.1)), float(0.6))).toVar();
  rough.subAssign(((jointAmt).mul(smoothstep(float(0.35), float(0.85), swirl))).mul(float(0.10)));
  c.mulAssign((float(1.0)).sub(((jointAmt).mul(smoothstep(float(0.4), float(0.9), swirl))).mul(float(0.07))));
  const crk = cracks((p).mul(float(2.6)), (P).mul(float(2.6)), float(0.85), float(0.028), float(0.50)).toVar();
  const crkFine = (cracks(((p).mul(float(7.0))).add(float(31.0)), (P).mul(float(7.0)), float(0.9), float(0.020), float(0.60))).mul(float(0.55)).toVar();
  const crack = clamp((crk).add(crkFine), float(0.0), float(1.0)).toVar();
  h.subAssign((crack).mul(float(0.12)));
  ao.subAssign((crack).mul(float(0.45)));
  c.assign(mix(c, (cDark).mul(float(0.80)), (crack).mul(float(0.42))));
  rough.addAssign((crack).mul(float(0.12)));
  const sp = worley(((p).mul(float(1.1))).add(float(7.3)), (P).mul(float(1.1)), float(0.9)).toVar();
  const spallCell = step(float(0.90), sp.w).toVar();
  const spall = ((spallCell).mul(smoothstep(float(0.16), float(0.44), sp.x).oneMinus())).mul(smoothstep(float(0.42), float(0.62), fbm01(fbm4(((p).mul(float(4.0))).add(float(2.0)), (P).mul(float(4.0)), float(0.5))))).toVar();
  h.subAssign((spall).mul(float(0.13)));
  ao.subAssign((spall).mul(float(0.35)));
  c.assign(mix(c, (mix(cDark, cMid, aggRnd)).mul(float(0.88)), (spall).mul(float(0.8))));
  rough.addAssign((spall).mul(float(0.10)));
  const spallRim = ((spall).mul((float(1.0)).sub(spall))).mul(float(4.0)).toVar();
  c.mulAssign((float(1.0)).add((spallRim).mul(float(0.10))));
  const ck = worley(domainWarp(((p).mul(float(5.6))).add(float(19.0)), (P).mul(float(5.6)), float(0.6), 3), (P).mul(float(5.6)), float(0.95)).toVar();
  const ckSel = step(float(0.90), ck.w).toVar();
  const ckSize = (float(0.20)).add((float(0.16)).mul(ck.z)).toVar();
  const ckShape = smoothstep(ckSize, (ckSize).mul(float(0.3)), (ck.x).mul((float(0.72)).add((float(0.56)).mul(fbm01(fbm3((p).mul(float(16.0)), (P).mul(float(16.0)), float(0.5))))))).toVar();
  const chip = (ckSel).mul(ckShape).toVar();
  c.assign(mix(c, mix((c).mul(float(0.74)), mix(cDark, cMid, sand.z), float(0.5)), (chip).mul(float(0.85))));
  h.subAssign((chip).mul(float(0.045)));
  ao.subAssign((chip).mul(float(0.24)));
  rough.addAssign((chip).mul(float(0.08)));
  const ckLip = max((ckSel).mul((smoothstep((ckSize).mul(float(1.25)), ckSize, ck.x)).sub(ckShape)), float(0.0)).toVar();
  c.mulAssign((float(1.0)).add((ckLip).mul(float(0.10))));
  const streak = fbm01(fbm5(vec2((p.x).mul(float(6.0)), (p.y).mul(float(2.0))), vec2((P.x).mul(float(6.0)), (P.y).mul(float(2.0))), float(0.55))).toVar();
  const runoff = (smoothstep(float(0.58), float(0.95), streak)).mul((float(0.35)).add((float(0.65)).mul(smoothstep(float(0.2), float(0.8), macro)))).toVar();
  c.mulAssign((float(1.0)).sub((runoff).mul(float(0.14))));
  rough.addAssign((runoff).mul(float(0.05)));
  const rustBleed = (smoothstep(float(0.72), float(0.98), (streak).mul((float(0.6)).add((float(0.5)).mul(tieRnd))))).mul(step(float(0.80), tieRnd)).toVar();
  c.assign(mix(c, authoredColor(0.42, 0.24, 0.12), (rustBleed).mul(float(0.45))));
  const cavity = (float(1.0)).sub(smoothstep(float(0.42), float(0.66), h)).toVar();
  c.assign(mix(c, authoredColor(0.20, 0.19, 0.17), (cavity).mul(float(0.35))));
  alb.assign(clamp(c, vec3(float(0.02)), vec3(float(0.85))));
  rough.assign(clamp(rough, float(0.48), float(0.98)));
  ao.assign(clamp(ao, float(0.15), float(1.0)));
  h.assign(clamp(h, float(0.0), float(1.0)));
  return Surface(alb, h, rough, metal, ao);
});

// BRICK: authored channel stack migrated from surfaces-arch.js.
export const brickSurface = Fn(([coords, seed]) => {
  const alb = vec3(0.5).toVar(), h = float(0.5).toVar();
  const rough = float(0.5).toVar(), metal = float(0).toVar(), ao = float(1).toVar();
  const P = vec2(float(8.0)).toVar();
  const COLS = float(6.0).toVar();
  const ROWS = float(18.0).toVar();
  const p = ((coords).mul(P)).add((seed).mul(float(9.1))).toVar();
  const rowF = (coords.y).mul(ROWS).toVar();
  const row = floor(rowF).toVar();
  const colF = ((coords.x).mul(COLS)).add((mod(row, float(2.0))).mul(float(0.5))).toVar();
  const col = floor(colF).toVar();
  const id = vec2(mod(col, COLS), row).toVar();
  const f = vec2(fract(colF), fract(rowF)).toVar();
  const rnd = hash42((id).add((seed).mul(float(3.0)))).toVar();
  const rnd2 = hash42((((id).mul(float(1.37))).add(float(21.0))).add(seed)).toVar();
  const rnd3 = hash42((((id).mul(float(0.73))).add(float(7.7))).add((seed).mul(float(1.9)))).toVar();
  const jitter = ((rnd.xy).sub(float(0.5))).mul(vec2(float(0.012), float(0.030))).toVar();
  const fj = (f).add(jitter).toVar();
  const JX = float(0.048).toVar();
  const JY = float(0.135).toVar();
  const dxj = min(fj.x, (float(1.0)).sub(fj.x)).toVar();
  const dyj = min(fj.y, (float(1.0)).sub(fj.y)).toVar();
  const shoulder = (float(0.74)).add((float(0.16)).mul(rnd3.w)).toVar();
  const ex = smoothstep((JX).mul(shoulder), (JX).mul(float(1.02)), dxj).toVar();
  const ey = smoothstep((JY).mul(shoulder), (JY).mul(float(1.02)), dyj).toVar();
  const face = min(ex, ey).toVar();
  const bp = ((vec2(fj.x, fj.y)).mul(vec2(float(3.0), float(1.0)))).add((rnd.zw).mul(float(17.0))).toVar();
  const BP = vec2(float(24.0)).toVar();
  const mSand = fbm01(fbm4((p).mul(float(20.0)), (P).mul(float(20.0)), float(0.5))).toVar();
  const mGrain = worley((p).mul(float(24.0)), (P).mul(float(24.0)), float(1.0)).toVar();
  const mortarRough = fbm01(fbm4((p).mul(float(20.0)), (P).mul(float(20.0)), float(0.55))).toVar();
  const mortarCol = mix(authoredColor(0.400, 0.388, 0.362), authoredColor(0.278, 0.272, 0.260), smoothstep(float(0.3), float(0.8), mortarRough)).toVar();
  mortarCol.mulAssign((float(0.84)).add((float(0.32)).mul(mSand)));
  mortarCol.mulAssign((float(0.88)).add((float(0.24)).mul(fbm01(fbm4((p).mul(float(6.0)), (P).mul(float(6.0)), float(0.6))))));
  mortarCol.assign(mix(mortarCol, authoredColor(0.235, 0.228, 0.215), (smoothstep(float(0.06), float(0.5), mGrain.x).oneMinus()).mul(float(0.40))));
  mortarCol.assign(mix(mortarCol, authoredColor(0.520, 0.505, 0.470), (smoothstep(float(0.02), float(0.30), worley(((p).mul(float(25.0))).add(float(4.0)), (P).mul(float(25.0)), float(1.0)).x).oneMinus()).mul(float(0.35))));
  const jointDepth = (float(0.10)).add((float(0.05)).mul(fbm01(fbm3((p).mul(float(1.2)), (P).mul(float(1.2)), float(0.5))))).toVar();
  const crumble = smoothstep(float(0.62), float(0.86), fbm01(fbm4(((p).mul(float(9.0))).add(float(4.0)), (P).mul(float(9.0)), float(0.5)))).toVar();
  jointDepth.addAssign((crumble).mul(float(0.09)));
  const mortarH = ((((mSand).sub(float(0.5))).negate()).mul(float(0.018))).sub((smoothstep(float(0.0), float(0.5), mGrain.x).oneMinus()).mul(float(0.012))).toVar();
  const faceN = fbm01(fbm5((bp).mul(float(2.2)), BP, float(0.5))).toVar();
  const faceFine = fbm01(fbm4((bp).mul(float(5.0)), (BP).mul(float(2.0)), float(0.5))).toVar();
  const facePore = worley((bp).mul(float(7.0)), (BP).mul(float(3.5)), float(1.0)).toVar();
  const poreCluster = smoothstep(float(0.42), float(0.78), fbm01(fbm4(((bp).mul(float(3.0))).add(float(8.0)), (BP).mul(float(1.5)), float(0.55)))).toVar();
  const pore = ((smoothstep((float(0.26)).add((float(0.16)).mul(facePore.z)), float(0.0), facePore.x)).mul(step(float(0.55), facePore.w))).mul(poreCluster).toVar();
  const cA = authoredColor(0.430, 0.238, 0.183).toVar();
  const cB = authoredColor(0.318, 0.183, 0.150).toVar();
  const cC = authoredColor(0.196, 0.132, 0.120).toVar();
  const cD = authoredColor(0.492, 0.392, 0.300).toVar();
  const cE = authoredColor(0.372, 0.288, 0.218).toVar();
  const brick = mix(cA, cB, rnd.z).toVar();
  brick.assign(mix(brick, cC, (step(float(0.90), rnd.w)).mul(float(0.70))));
  brick.assign(mix(brick, cD, (step(float(0.94), rnd2.x)).mul(float(0.62))));
  brick.assign(mix(brick, cE, (step(float(0.55), rnd2.y)).mul(float(0.50))));
  brick.mulAssign((float(0.88)).add((float(0.24)).mul(rnd3.x)));
  brick.mulAssign((float(0.86)).add((float(0.28)).mul(faceN)));
  const faceGrain = fbm01(fbm4((bp).mul(float(8.0)), (BP).mul(float(4.0)), float(0.55))).toVar();
  brick.mulAssign((float(0.87)).add((float(0.26)).mul(faceGrain)));
  brick.assign(mix(brick, (brick).mul(float(1.22)), (smoothstep(float(0.55), float(0.9), faceFine)).mul(float(0.5))));
  brick.assign(mix(brick, (brick).mul(float(0.62)), (pore).mul(float(0.85))));
  brick.assign(mix(brick, (brick).mul(float(0.72)), (smoothstep(float(0.0), float(0.34), facePore.x).oneMinus()).mul(step(float(0.86), facePore.z))));
  brick.assign(mix(brick, authoredColor(0.62, 0.58, 0.50), (smoothstep(float(0.86), float(0.98), faceFine)).mul(float(0.35))));
  const faceH = (((float(0.72)).add(((faceN).sub(float(0.5))).mul(float(0.05)))).add(((faceFine).sub(float(0.5))).mul(float(0.025)))).add(((rnd2.z).sub(float(0.5))).mul(float(0.05))).toVar();
  faceH.subAssign((pore).mul(float(0.075)));
  const edgeD = min((dxj).div(JX), (dyj).div(JY)).toVar();
  const chipNoise = fbm01(fbm4(((bp).mul(float(6.0))).add(float(3.0)), (BP).mul(float(3.0)), float(0.5))).toVar();
  const chip = ((smoothstep(float(0.30), float(1.7), edgeD).oneMinus()).mul(smoothstep(float(0.60), float(0.80), chipNoise))).mul(step(float(0.66), rnd3.z)).toVar();
  faceH.subAssign((chip).mul(float(0.17)));
  brick.assign(mix(brick, ((brick).mul(float(0.72))).add(authoredColor(0.20, 0.13, 0.09)), (chip).mul(float(0.65))));
  const m = face.toVar();
  h.assign(mix(((float(0.72)).sub(jointDepth)).add(mortarH), faceH, m));
  const c = mix(mortarCol, brick, m).toVar();
  const brickRough = ((float(0.58)).add((float(0.32)).mul(rnd2.z))).add(((rnd3.y).sub(float(0.5))).mul(float(0.20))).toVar();
  rough.assign(mix(((float(0.88)).add((float(0.10)).mul(mSand))).add((float(0.06)).mul((mortarRough).sub(float(0.5)))), (((brickRough).add((float(0.14)).mul(faceN))).add((float(0.10)).mul((faceGrain).sub(float(0.5))))).add((chip).mul(float(0.14))), m));
  ao.assign(mix(float(0.34), float(1.0), smoothstep(float(0.0), float(0.75), face)));
  ao.subAssign((chip).mul(float(0.30)));
  metal.assign(float(0.0));
  const smear = (smoothstep(float(0.5), float(1.0), (float(1.0)).sub(face))).mul(smoothstep(float(0.55), float(0.9), fbm01(fbm4((p).mul(float(14.0)), (P).mul(float(14.0)), float(0.5))))).toVar();
  c.assign(mix(c, (mortarCol).mul(float(1.05)), (smear).mul(float(0.5))));
  const soilB = fbm01(fbm4(domainWarp(((p).mul(float(1.8))).add(float(27.0)), (P).mul(float(1.8)), float(0.6), 3), (P).mul(float(1.8)), float(0.58))).toVar();
  soilB.assign(clamp((((soilB).sub(float(0.5))).mul(float(2.5))).add(float(0.5)), float(0.0), float(1.0)));
  c.mulAssign((float(0.845)).add((float(0.33)).mul(soilB)));
  const efflo = smoothstep(float(0.62), float(0.96), fbm01(fbm4(domainWarp((p).mul(float(2.6)), (P).mul(float(2.6)), float(0.8), 3), (P).mul(float(2.6)), float(0.5)))).toVar();
  efflo.mulAssign(mix(float(1.0), float(0.35), m));
  c.assign(mix(c, authoredColor(0.66, 0.652, 0.632), (efflo).mul(float(0.5))));
  rough.addAssign((efflo).mul(float(0.10)));
  const streak = fbm01(fbm5(vec2((p.x).mul(float(7.0)), (p.y).mul(float(2.3))), vec2((P.x).mul(float(7.0)), (P.y).mul(float(2.0))), float(0.55))).toVar();
  const runoff = smoothstep(float(0.50), float(0.92), streak).toVar();
  c.mulAssign((float(1.0)).sub((runoff).mul(float(0.16))));
  const crack = cracks((p).mul(float(2.2)), (P).mul(float(2.2)), float(0.85), float(0.038), float(0.58)).toVar();
  h.subAssign((crack).mul(float(0.10)));
  ao.subAssign((crack).mul(float(0.45)));
  c.assign(mix(c, (c).mul(float(0.35)), (crack).mul(float(0.7))));
  const cavity = (float(1.0)).sub(smoothstep(float(0.50), float(0.74), h)).toVar();
  c.assign(mix(c, authoredColor(0.16, 0.15, 0.14), (cavity).mul(float(0.32))));
  alb.assign(clamp(c, vec3(float(0.02)), vec3(float(0.85))));
  rough.assign(clamp(rough, float(0.35), float(0.99)));
  ao.assign(clamp(ao, float(0.12), float(1.0)));
  h.assign(clamp(h, float(0.0), float(1.0)));
  return Surface(alb, h, rough, metal, ao);
});

// PLASTER: authored channel stack migrated from surfaces-arch.js.
export const plasterSurface = Fn(([coords, seed]) => {
  const alb = vec3(0.5).toVar(), h = float(0.5).toVar();
  const rough = float(0.5).toVar(), metal = float(0).toVar(), ao = float(1).toVar();
  const P = vec2(float(8.0)).toVar();
  const p = ((coords).mul(P)).add((seed).mul(float(5.3))).toVar();
  const sw = shear((p).mul(float(1.5)), float(1.0), float(3.0)).toVar();
  const trowel = fbm01(fbm5(sw, shearPeriod((P).mul(float(1.5)), float(3.0)), float(0.55))).toVar();
  const skim = fbm01(fbm5((p).mul(float(12.0)), (P).mul(float(12.0)), float(0.5))).toVar();
  const micro = fbm01(fbm3((p).mul(float(24.0)), (P).mul(float(24.0)), float(0.5))).toVar();
  const macro = fbm01(fbm3((p).mul(float(0.6)), (P).mul(float(0.6)), float(0.6))).toVar();
  const cBase = authoredColor(0.598, 0.578, 0.538).toVar();
  const cWarm = authoredColor(0.512, 0.462, 0.395).toVar();
  const cGrey = authoredColor(0.382, 0.378, 0.372).toVar();
  const c = mix(cBase, cWarm, smoothstep(float(0.3), float(0.8), macro)).toVar();
  c.mulAssign((float(0.94)).add((float(0.12)).mul(skim)));
  c.assign(mix(c, cGrey, (smoothstep(float(0.45), float(0.95), trowel)).mul(float(0.42))));
  c.assign(mix(c, (cBase).mul(float(1.10)), (smoothstep(float(0.15), float(0.55), trowel).oneMinus()).mul(float(0.30))));
  h.assign((((float(0.70)).add(((trowel).sub(float(0.5))).mul(float(0.10)))).add(((skim).sub(float(0.5))).mul(float(0.030)))).add(((micro).sub(float(0.5))).mul(float(0.012))));
  rough.assign(((float(0.80)).add(((skim).sub(float(0.5))).mul(float(0.12)))).sub((smoothstep(float(0.5), float(0.9), trowel)).mul(float(0.10))));
  ao.assign(float(1.0));
  metal.assign(float(0.0));
  const lapUv = shear((p).mul(float(0.7)), float(1.0), float(1.0)).toVar();
  const lapF = (lapUv.y).add((fbm01(fbm3((p).mul(float(1.1)), (P).mul(float(1.1)), float(0.6)))).mul(float(1.4))).toVar();
  const lapI = floor(lapF).toVar();
  const lapT = fract(lapF).toVar();
  const lapR = hash11(((lapI).mul(float(1.71))).add((seed).mul(float(2.3)))).toVar();
  c.mulAssign((float(0.885)).add((float(0.240)).mul(lapR)));
  rough.addAssign(((lapR).sub(float(0.5))).mul(float(0.10)));
  const dampB = fbm01(fbm4(domainWarp(((p).mul(float(1.6))).add(float(3.7)), (P).mul(float(1.6)), float(0.7), 3), (P).mul(float(1.6)), float(0.58))).toVar();
  dampB.assign(clamp((((dampB).sub(float(0.5))).mul(float(2.6))).add(float(0.5)), float(0.0), float(1.0)));
  c.mulAssign((float(0.80)).add((float(0.42)).mul(dampB)));
  rough.addAssign(((dampB).sub(float(0.5))).mul(float(0.12)));
  const soil2 = fbm01(fbm4(domainWarp(((p).mul(float(3.4))).add(float(21.0)), (P).mul(float(3.4)), float(0.55), 3), (P).mul(float(3.4)), float(0.55))).toVar();
  soil2.assign(clamp((((soil2).sub(float(0.5))).mul(float(2.4))).add(float(0.5)), float(0.0), float(1.0)));
  c.mulAssign((float(0.875)).add((float(0.26)).mul(soil2)));
  const wash = fbm01(fbm4(((p).mul(float(8.0))).add(float(6.0)), (P).mul(float(8.0)), float(0.5))).toVar();
  wash.assign(clamp((((wash).sub(float(0.5))).mul(float(2.2))).add(float(0.5)), float(0.0), float(1.0)));
  c.mulAssign((float(0.925)).add((float(0.155)).mul(wash)));
  const lapEdge = ((float(1.0)).sub(smoothstep(float(0.0), float(0.05), lapT))).mul((float(0.35)).add((float(0.65)).mul(lapR))).toVar();
  h.addAssign(((lapEdge).mul(float(0.022))).sub(((lapR).sub(float(0.5))).mul(float(0.014))));
  c.mulAssign((float(1.0)).add((lapEdge).mul(float(0.07))));
  const tooth = worley((p).mul(float(20.0)), (P).mul(float(20.0)), float(1.0)).toVar();
  const grain = smoothstep(float(0.06), float(0.46), tooth.x).oneMinus().toVar();
  const grainSel = (float(0.40)).add((float(0.60)).mul(step(float(0.32), tooth.z))).toVar();
  h.addAssign(((grain).mul(grainSel)).mul(float(0.030)));
  ao.subAssign((grain).mul(float(0.07)));
  c.mulAssign((float(1.0)).add((((grain).mul(grainSel)).sub(float(0.20))).mul(float(0.16))));
  rough.addAssign((((tooth.z).sub(float(0.5))).mul(float(0.11))).add((grain).mul(float(0.05))));
  const trough = smoothstep(float(0.52), float(0.86), tooth.x).toVar();
  c.assign(mix(c, (c).mul(float(0.84)), (trough).mul(float(0.40))));
  const ph = worley((p).mul(float(22.0)), (P).mul(float(22.0)), float(1.0)).toVar();
  const hole = (smoothstep(float(0.0), float(0.24), ph.x).oneMinus()).mul(step(float(0.80), ph.w)).toVar();
  h.subAssign((hole).mul(float(0.06)));
  ao.subAssign((hole).mul(float(0.4)));
  const hair = cracks((p).mul(float(9.0)), (P).mul(float(9.0)), float(0.9), float(0.016), float(0.52)).toVar();
  hair.addAssign((cracks(((p).mul(float(16.0))).add(float(6.0)), (P).mul(float(16.0)), float(0.95), float(0.015), float(0.62))).mul(float(0.5)));
  hair.assign(clamp(hair, float(0.0), float(1.0)));
  h.subAssign((hair).mul(float(0.030)));
  ao.subAssign((hair).mul(float(0.18)));
  c.assign(mix(c, (c).mul(float(0.80)), (hair).mul(float(0.45))));
  const crack = cracks(((p).mul(float(4.5))).add(float(17.0)), (P).mul(float(4.5)), float(0.8), float(0.018), float(0.62)).toVar();
  h.subAssign((crack).mul(float(0.16)));
  ao.subAssign((crack).mul(float(0.6)));
  c.assign(mix(c, authoredColor(0.300, 0.278, 0.250), (crack).mul(float(0.8))));
  const blowMask = fbm01(fbm4(domainWarp(((p).mul(float(1.05))).add(float(9.0)), (P).mul(float(1.05)), float(1.1), 3), (P).mul(float(1.05)), float(0.55))).toVar();
  const blow = smoothstep(float(0.775), float(0.845), blowMask).toVar();
  const blowEdge = (smoothstep(float(0.745), float(0.790), blowMask)).sub(blow).toVar();
  const substrate = mix(authoredColor(0.360, 0.245, 0.195), authoredColor(0.430, 0.400, 0.360), fbm01(fbm4((p).mul(float(9.0)), (P).mul(float(9.0)), float(0.5)))).toVar();
  substrate.mulAssign((float(0.85)).add((float(0.3)).mul(fbm01(fbm3((p).mul(float(20.0)), (P).mul(float(20.0)), float(0.5))))));
  c.assign(mix(c, substrate, (blow).mul(float(0.85))));
  h.subAssign((blow).mul(float(0.13)));
  ao.subAssign((blow).mul(float(0.26)));
  rough.addAssign((blow).mul(float(0.10)));
  c.addAssign((blowEdge).mul(float(0.06)));
  h.addAssign((blowEdge).mul(float(0.02)));
  const ck = worley(domainWarp(((p).mul(float(4.2))).add(float(13.0)), (P).mul(float(4.2)), float(0.6), 3), (P).mul(float(4.2)), float(0.95)).toVar();
  const ckSel = step(float(0.930), ck.w).toVar();
  const ckSize = (float(0.22)).add((float(0.20)).mul(ck.z)).toVar();
  const ckShape = smoothstep(ckSize, (ckSize).mul(float(0.3)), (ck.x).mul((float(0.70)).add((float(0.60)).mul(fbm01(fbm3((p).mul(float(16.0)), (P).mul(float(16.0)), float(0.5))))))).toVar();
  const chip = (ckSel).mul(ckShape).toVar();
  const coat = mix(c, authoredColor(0.392, 0.336, 0.284), float(0.52)).toVar();
  coat.mulAssign((float(0.90)).add((float(0.20)).mul(fbm01(fbm3((p).mul(float(18.0)), (P).mul(float(18.0)), float(0.5))))));
  c.assign(mix(c, coat, (chip).mul(float(0.58))));
  h.subAssign((chip).mul(float(0.05)));
  ao.subAssign((chip).mul(float(0.26)));
  rough.addAssign((chip).mul(float(0.09)));
  const ckLip = max((ckSel).mul((smoothstep((ckSize).mul(float(1.25)), ckSize, ck.x)).sub(ckShape)), float(0.0)).toVar();
  c.mulAssign((float(1.0)).add((ckLip).mul(float(0.10))));
  h.addAssign((ckLip).mul(float(0.010)));
  const stain = fbm01(fbm5(vec2((p.x).mul(float(1.6)), (p.y).mul(float(3.2))), vec2((P.x).mul(float(1.6)), (P.y).mul(float(3.0))), float(0.6))).toVar();
  const tide = (smoothstep(float(0.60), float(0.78), stain)).mul((float(1.0)).sub(smoothstep(float(0.78), float(0.94), stain))).toVar();
  c.assign(mix(c, authoredColor(0.400, 0.330, 0.245), (tide).mul(float(0.45))));
  c.mulAssign((float(1.0)).sub((smoothstep(float(0.50), float(0.95), stain)).mul(float(0.34))));
  rough.addAssign((tide).mul(float(0.05)));
  const mould = (smoothstep(float(0.72), float(0.95), fbm01(fbm5(((p).mul(float(4.0))).add(float(25.0)), (P).mul(float(4.0)), float(0.6))))).mul(smoothstep(float(0.45), float(0.8), stain)).toVar();
  c.assign(mix(c, authoredColor(0.085, 0.090, 0.080), (mould).mul(float(0.7))));
  rough.addAssign((mould).mul(float(0.08)));
  const cavity = (float(1.0)).sub(smoothstep(float(0.48), float(0.72), h)).toVar();
  c.assign(mix(c, authoredColor(0.22, 0.21, 0.19), (cavity).mul(float(0.30))));
  alb.assign(clamp(c, vec3(float(0.02)), vec3(float(0.88))));
  rough.assign(clamp(rough, float(0.35), float(0.99)));
  ao.assign(clamp(ao, float(0.15), float(1.0)));
  h.assign(clamp(h, float(0.0), float(1.0)));
  return Surface(alb, h, rough, metal, ao);
});

// TILE: authored channel stack migrated from surfaces-arch.js.
export const tileSurface = Fn(([coords, seed]) => {
  const alb = vec3(0.5).toVar(), h = float(0.5).toVar();
  const rough = float(0.5).toVar(), metal = float(0).toVar(), ao = float(1).toVar();
  const P = vec2(float(8.0)).toVar();
  const N = float(6.0).toVar();
  const p = ((coords).mul(P)).add((seed).mul(float(4.4))).toVar();
  const tp = (coords).mul(N).toVar();
  const id = floor(tp).toVar();
  const f = fract(tp).toVar();
  const rnd = hash42((id).add(seed)).toVar();
  const J = float(0.045).toVar();
  const dxj = min(f.x, (float(1.0)).sub(f.x)).toVar();
  const dyj = min(f.y, (float(1.0)).sub(f.y)).toVar();
  const ex = smoothstep((J).mul(float(0.70)), (J).mul(float(1.02)), dxj).toVar();
  const ey = smoothstep((J).mul(float(0.70)), (J).mul(float(1.02)), dyj).toVar();
  const face = min(ex, ey).toVar();
  const glaze = fbm01(fbm4(((f).mul(float(6.0))).add((rnd.xy).mul(float(21.0))), vec2(float(48.0)), float(0.5))).toVar();
  const cTile = mix(authoredColor(0.700, 0.690, 0.660), authoredColor(0.470, 0.500, 0.505), (rnd.z).mul(float(0.7))).toVar();
  cTile.mulAssign((float(0.93)).add((float(0.13)).mul(glaze)));
  cTile.mulAssign((float(0.92)).add((float(0.16)).mul(rnd.y)));
  const grout = fbm01(fbm4((p).mul(float(20.0)), (P).mul(float(20.0)), float(0.5))).toVar();
  const cGrout = (authoredColor(0.400, 0.385, 0.360)).mul((float(0.85)).add((float(0.3)).mul(grout))).toVar();
  cGrout.assign(mix(cGrout, authoredColor(0.13, 0.13, 0.12), float(0.45)));
  const m = face.toVar();
  h.assign(mix((float(0.76)).sub(((grout).sub(float(0.5))).mul(float(0.02))), (float(0.82)).add(((rnd.w).sub(float(0.5))).mul(float(0.04))), m));
  const c = mix(cGrout, cTile, m).toVar();
  rough.assign(mix(float(0.92), ((float(0.20)).add((float(0.22)).mul(glaze))).add(((rnd.z).sub(float(0.5))).mul(float(0.14))), m));
  ao.assign(mix(float(0.40), float(1.0), smoothstep(float(0.0), float(0.8), face)));
  metal.assign(float(0.0));
  const broken = step(float(0.90), rnd.x).toVar();
  const crack = (cracks(((f).mul(float(3.0))).add((rnd.yz).mul(float(9.0))), vec2(float(24.0)), float(0.85), float(0.04), float(0.45))).mul(m).toVar();
  c.assign(mix(c, (c).mul(float(0.3)), (crack).mul(float(0.8))));
  h.subAssign((crack).mul(float(0.08)));
  ao.subAssign((crack).mul(float(0.5)));
  const sub = authoredColor(0.330, 0.300, 0.270).toVar();
  c.assign(mix(c, sub, ((broken).mul(m)).mul(float(0.9))));
  h.subAssign(((broken).mul(m)).mul(float(0.14)));
  rough.assign(mix(rough, float(0.95), (broken).mul(m)));
  const wear = smoothstep(float(0.45), float(0.95), fbm01(fbm4((p).mul(float(2.0)), (P).mul(float(2.0)), float(0.55)))).toVar();
  rough.addAssign(((wear).mul(float(0.20))).mul(m));
  c.mulAssign((float(1.0)).sub((wear).mul(float(0.12))));
  const cavity = (float(1.0)).sub(smoothstep(float(0.68), float(0.80), h)).toVar();
  c.assign(mix(c, authoredColor(0.14, 0.13, 0.12), (cavity).mul(float(0.35))));
  alb.assign(clamp(c, vec3(float(0.02)), vec3(float(0.85))));
  rough.assign(clamp(rough, float(0.12), float(0.95)));
  ao.assign(clamp(ao, float(0.15), float(1.0)));
  h.assign(clamp(h, float(0.0), float(1.0)));
  return Surface(alb, h, rough, metal, ao);
});

