import { Fn, abs, clamp, float, fract, max, mix, smoothstep, step, vec2, vec3 } from 'three/tsl';
import { authoredColor } from '../color-tsl.js';
import { Surface } from './surface.js';
import { billow5, cracks, fbm01, fbm3, fbm4, fbm5, shear, shearPeriod, warp as domainWarp, worley } from '../noise-tsl.js';

// ASPHALT: authored channel stack migrated from surfaces-ground.js.
export const asphaltSurface = Fn(([coords, seed]) => {
  const alb = vec3(0.5).toVar(), h = float(0.5).toVar();
  const rough = float(0.5).toVar(), metal = float(0).toVar(), ao = float(1).toVar();
  const P = vec2(float(8.0)).toVar();
  const p = ((coords).mul(P)).add((seed).mul(float(6.9))).toVar();
  const macro = fbm01(fbm4((p).mul(float(0.55)), (P).mul(float(0.5)), float(0.6))).toVar();
  const mid = fbm01(fbm5((p).mul(float(3.0)), (P).mul(float(3.0)), float(0.5))).toVar();
  const fine = fbm01(fbm4((p).mul(float(16.0)), (P).mul(float(16.0)), float(0.5))).toVar();
  const cFresh = authoredColor(0.115, 0.115, 0.122).toVar();
  const cWorn = authoredColor(0.300, 0.298, 0.295).toVar();
  const c = mix(cFresh, cWorn, (smoothstep(float(0.25), float(0.85), macro)).mul(float(0.85))).toVar();
  c.mulAssign((float(0.94)).add((float(0.12)).mul(fine)));
  h.assign((float(0.60)).add(((mid).sub(float(0.5))).mul(float(0.06))));
  rough.assign(((float(0.78)).add(((mid).sub(float(0.5))).mul(float(0.10)))).add(((fine).sub(float(0.5))).mul(float(0.14))));
  metal.assign(float(0.0));
  ao.assign(float(1.0));
  const ap = domainWarp(p, P, float(0.10), 3).toVar();
  const big = worley((ap).mul(float(12.0)), (P).mul(float(12.0)), float(1.0)).toVar();
  const bigM = smoothstep(float(0.16), float(0.40), big.x).oneMinus().toVar();
  const bigExposed = (bigM).mul(smoothstep(float(0.30), float(0.62), (fbm01(fbm4(((p).mul(float(2.2))).add(float(3.0)), (P).mul(float(2.0)), float(0.5)))).add((big.w).mul(float(0.5))))).toVar();
  const small = worley(((ap).mul(float(22.0))).add(float(7.0)), (P).mul(float(22.0)), float(1.0)).toVar();
  const smallM = smoothstep(float(0.10), float(0.36), small.x).oneMinus().toVar();
  const smallExposed = (smallM).mul(step(float(0.30), small.w)).toVar();
  const grit = worley(((ap).mul(float(28.0))).add(float(3.0)), (P).mul(float(28.0)), float(1.0)).toVar();
  const gritM = (smoothstep(float(0.06), float(0.32), grit.x).oneMinus()).mul(step(float(0.45), grit.z)).toVar();
  const stoneA = authoredColor(0.400, 0.392, 0.378).toVar();
  const stoneB = authoredColor(0.210, 0.200, 0.192).toVar();
  const stoneC = authoredColor(0.560, 0.520, 0.470).toVar();
  const stone = mix(stoneA, stoneB, big.z).toVar();
  stone.assign(mix(stone, stoneC, step(float(0.90), big.w)));
  c.assign(mix(c, stone, (bigExposed).mul(float(0.52))));
  c.assign(mix(c, mix(stoneA, stoneC, small.z), (smallExposed).mul(float(0.22))));
  c.assign(mix(c, mix(stoneB, stoneA, grit.z), (gritM).mul(float(0.14))));
  h.addAssign(((((bigExposed).mul(float(0.15))).mul((float(0.6)).add((float(0.6)).mul(big.z)))).add((smallExposed).mul(float(0.065)))).add((gritM).mul(float(0.022))));
  rough.addAssign(((bigExposed).mul((float(0.10)).sub((float(0.22)).mul(big.z)))).add((smallExposed).mul((float(0.06)).sub((float(0.14)).mul(small.z)))));
  const voidM = (smoothstep(float(0.50), float(0.85), big.x)).mul(smoothstep(float(0.28), float(0.6), small.x)).toVar();
  h.subAssign((voidM).mul(float(0.10)));
  ao.subAssign((voidM).mul(float(0.14)));
  const lane = (abs((fract(((coords.x).mul(float(1.0))).add(float(0.25)))).sub(float(0.5)))).mul(float(2.0)).toVar();
  const polish = ((float(1.0)).sub(smoothstep(float(0.10), float(0.62), lane))).mul(smoothstep(float(0.25), float(0.65), fbm01(fbm4(vec2((p.x).mul(float(0.7)), (p.y).mul(float(5.0))), vec2(P.x, (P.y).mul(float(5.0))), float(0.5))))).toVar();
  rough.subAssign((polish).mul(float(0.16)));
  h.subAssign((polish).mul(float(0.012)));
  c.assign(mix(c, ((c).mul(float(0.78))).add(authoredColor(0.045, 0.045, 0.048)), (polish).mul(float(0.45))));
  const rep = worley(domainWarp(((p).mul(float(0.5))).add(float(13.0)), (P).mul(float(0.5)), float(1.6), 3), (P).mul(float(0.5)), float(0.9)).toVar();
  const inPatch = step(float(0.72), rep.w).toVar();
  const patchEdge = ((float(1.0)).sub(smoothstep(float(0.0), float(0.06), (rep.y).sub(rep.x)))).mul(inPatch).toVar();
  c.assign(mix(c, (cFresh).mul((float(0.85)).add((float(0.35)).mul(fine))), (inPatch).mul(float(0.20))));
  rough.assign(mix(rough, float(0.84), (inPatch).mul(float(0.22))));
  h.subAssign((patchEdge).mul(float(0.07)));
  ao.subAssign((patchEdge).mul(float(0.20)));
  c.assign(mix(c, (cFresh).mul(float(0.5)), (patchEdge).mul(float(0.35))));
  const tar = (patchEdge).mul(smoothstep(float(0.4), float(0.7), fbm01(fbm3((p).mul(float(6.0)), (P).mul(float(6.0)), float(0.5))))).toVar();
  rough.subAssign((tar).mul(float(0.35)));
  c.assign(mix(c, authoredColor(0.055, 0.055, 0.058), (tar).mul(float(0.7))));
  const gator = cracks((p).mul(float(3.4)), (P).mul(float(3.4)), float(0.9), float(0.032), float(0.56)).toVar();
  const thermal = cracks(((p).mul(float(0.9))).add(float(41.0)), (P).mul(float(0.9)), float(0.75), float(0.05), float(0.70)).toVar();
  const crack = clamp((gator).add(thermal), float(0.0), float(1.0)).toVar();
  h.subAssign((crack).mul(float(0.16)));
  ao.subAssign((crack).mul(float(0.30)));
  c.assign(mix(c, authoredColor(0.045, 0.043, 0.042), (crack).mul(float(0.85))));
  rough.addAssign((crack).mul(float(0.12)));
  const oil = smoothstep(float(0.68), float(0.90), fbm01(fbm4(domainWarp(((p).mul(float(1.8))).add(float(31.0)), (P).mul(float(1.8)), float(0.9), 3), (P).mul(float(1.8)), float(0.55)))).toVar();
  c.assign(mix(c, authoredColor(0.045, 0.043, 0.046), (oil).mul(float(0.6))));
  rough.subAssign((oil).mul(float(0.16)));
  const dust = (smoothstep(float(0.30), float(0.55), h).oneMinus()).mul(smoothstep(float(0.35), float(0.75), macro)).toVar();
  c.assign(mix(c, authoredColor(0.420, 0.390, 0.340), (dust).mul(float(0.35))));
  rough.addAssign((dust).mul(float(0.10)));
  alb.assign(clamp(c, vec3(float(0.02)), vec3(float(0.75))));
  rough.assign(clamp(rough, float(0.44), float(0.99)));
  ao.assign(clamp(ao, float(0.68), float(1.0)));
  h.assign(clamp(h, float(0.0), float(1.0)));
  return Surface(alb, h, rough, metal, ao);
});

// DIRT: authored channel stack migrated from surfaces-ground.js.
export const dirtSurface = Fn(([coords, seed]) => {
  const alb = vec3(0.5).toVar(), h = float(0.5).toVar();
  const rough = float(0.5).toVar(), metal = float(0).toVar(), ao = float(1).toVar();
  const P = vec2(float(8.0)).toVar();
  const p = ((coords).mul(P)).add((seed).mul(float(3.4))).toVar();
  const macro = fbm01(fbm4((p).mul(float(0.6)), (P).mul(float(0.6)), float(0.62))).toVar();
  const clump = billow5(domainWarp((p).mul(float(3.0)), (P).mul(float(3.0)), float(0.6), 3), (P).mul(float(3.0)), float(0.55)).toVar();
  const fine = fbm01(fbm4((p).mul(float(14.0)), (P).mul(float(14.0)), float(0.5))).toVar();
  const micro = fbm01(fbm3((p).mul(float(22.0)), (P).mul(float(22.0)), float(0.5))).toVar();
  const cDry = authoredColor(0.430, 0.350, 0.255).toVar();
  const cWet = authoredColor(0.185, 0.140, 0.100).toVar();
  const cPale = authoredColor(0.560, 0.490, 0.385).toVar();
  const c = mix(cDry, cPale, smoothstep(float(0.45), float(0.9), macro)).toVar();
  c.assign(mix(c, cWet, (smoothstep(float(0.15), float(0.55), macro).oneMinus()).mul(float(0.8))));
  c.mulAssign((float(0.94)).add((float(0.11)).mul(fine)));
  c.mulAssign((float(0.975)).add((float(0.05)).mul(micro)));
  h.assign((((float(0.55)).add(((macro).sub(float(0.5))).mul(float(0.14)))).add(((clump).sub(float(0.5))).mul(float(0.16)))).add(((fine).sub(float(0.5))).mul(float(0.075))));
  rough.assign(((float(0.88)).add(((fine).sub(float(0.5))).mul(float(0.14)))).add(((micro).sub(float(0.5))).mul(float(0.10))));
  metal.assign(float(0.0));
  ao.assign(float(1.0));
  const pan = smoothstep(float(0.35), float(0.65), macro).toVar();
  const mud = (cracks((p).mul(float(2.4)), (P).mul(float(2.4)), float(0.85), float(0.045), float(0.35))).mul(pan).toVar();
  h.subAssign((mud).mul(float(0.16)));
  ao.subAssign((mud).mul(float(0.32)));
  c.assign(mix(c, (cWet).mul(float(0.7)), (mud).mul(float(0.75))));
  const plateLift = (smoothstep(float(0.0), float(0.10), mud).oneMinus()).mul(pan).toVar();
  h.addAssign((plateLift).mul(float(0.01)));
  const st = worley((p).mul(float(11.0)), (P).mul(float(11.0)), float(1.0)).toVar();
  const stone = (smoothstep(float(0.11), float(0.30), st.x).oneMinus()).mul(step(float(0.62), st.w)).toVar();
  const scol = mix(authoredColor(0.330, 0.315, 0.295), authoredColor(0.600, 0.575, 0.540), st.z).toVar();
  c.assign(mix(c, scol, (stone).mul(float(0.6))));
  h.addAssign((stone).mul(float(0.085)));
  rough.assign(mix(rough, (float(0.52)).add((float(0.28)).mul(st.z)), (stone).mul(float(0.8))));
  ao.subAssign(((smoothstep(float(0.28), float(0.36), st.x).oneMinus()).mul(step(float(0.62), st.w))).mul(float(0.10)));
  const grit = worley((p).mul(float(22.0)), (P).mul(float(22.0)), float(1.0)).toVar();
  const gritM = (smoothstep(float(0.08), float(0.26), grit.x).oneMinus()).mul(step(float(0.55), grit.w)).toVar();
  c.assign(mix(c, mix(scol, cPale, grit.z), (gritM).mul(float(0.4))));
  h.addAssign((gritM).mul(float(0.015)));
  const litter = smoothstep(float(0.70), float(0.86), fbm01(fbm4(shear((p).mul(float(8.0)), float(1.0), float(5.0)), shearPeriod((P).mul(float(8.0)), float(5.0)), float(0.5)))).toVar();
  litter.mulAssign(smoothstep(float(0.4), float(0.8), macro));
  c.assign(mix(c, authoredColor(0.330, 0.290, 0.160), (litter).mul(float(0.5))));
  h.addAssign((litter).mul(float(0.012)));
  rough.addAssign((litter).mul(float(0.05)));
  const moss = (smoothstep(float(0.74), float(0.92), fbm01(fbm5(((p).mul(float(4.5))).add(float(19.0)), (P).mul(float(4.5)), float(0.6))))).mul(smoothstep(float(0.1), float(0.5), macro).oneMinus()).toVar();
  c.assign(mix(c, authoredColor(0.150, 0.185, 0.105), (moss).mul(float(0.65))));
  const cavity = (float(1.0)).sub(smoothstep(float(0.40), float(0.70), h)).toVar();
  ao.subAssign((cavity).mul(float(0.14)));
  alb.assign(clamp(c, vec3(float(0.02)), vec3(float(0.72))));
  rough.assign(clamp(rough, float(0.45), float(0.99)));
  ao.assign(clamp(ao, float(0.72), float(1.0)));
  h.assign(clamp(h, float(0.0), float(1.0)));
  return Surface(alb, h, rough, metal, ao);
});

// GRAVEL: authored channel stack migrated from surfaces-ground.js.
export const gravelSurface = Fn(([coords, seed]) => {
  const alb = vec3(0.5).toVar(), h = float(0.5).toVar();
  const rough = float(0.5).toVar(), metal = float(0).toVar(), ao = float(1).toVar();
  const P = vec2(float(8.0)).toVar();
  const p = ((coords).mul(P)).add((seed).mul(float(2.7))).toVar();
  const bed = fbm01(fbm4((p).mul(float(1.3)), (P).mul(float(1.3)), float(0.55))).toVar();
  const a = worley((p).mul(float(5.5)), (P).mul(float(5.5)), float(1.0)).toVar();
  const b = worley(((p).mul(float(10.0))).add(float(5.0)), (P).mul(float(10.0)), float(1.0)).toVar();
  const cSm = worley(((p).mul(float(21.0))).add(float(11.0)), (P).mul(float(21.0)), float(1.0)).toVar();
  const sA = (smoothstep(float(0.10), float(0.36), a.x).oneMinus()).mul(step(float(0.44), a.w)).toVar();
  const sB = (smoothstep(float(0.08), float(0.30), b.x).oneMinus()).mul(step(float(0.62), b.w)).toVar();
  const sC = (smoothstep(float(0.06), float(0.24), cSm.x).oneMinus()).mul(step(float(0.74), cSm.w)).toVar();
  const ha = ((sA).mul(float(0.15))).mul((float(0.5)).add(a.z)).toVar();
  const hb = ((sB).mul(float(0.09))).mul((float(0.5)).add(b.z)).toVar();
  const hc = (sC).mul(float(0.025)).toVar();
  h.assign((((float(0.54)).add(((bed).sub(float(0.5))).mul(float(0.11)))).add(max(max(ha, hb), hc))).add((float(0.22)).mul((ha).add(hb))));
  const s1 = authoredColor(0.372, 0.356, 0.332).toVar();
  const s2 = authoredColor(0.232, 0.220, 0.208).toVar();
  const s3 = authoredColor(0.462, 0.438, 0.400).toVar();
  const s4 = authoredColor(0.352, 0.276, 0.220).toVar();
  const top = mix(s1, s2, a.z).toVar();
  top.assign(mix(top, s3, step(float(0.78), a.w)));
  top.assign(mix(top, s4, (step(float(0.90), b.w)).mul(float(0.7))));
  const cBed = authoredColor(0.362, 0.336, 0.294).toVar();
  const c = mix(cBed, top, clamp((((sA).mul(float(0.70))).add((sB).mul(float(0.42)))).add((sC).mul(float(0.16))), float(0.0), float(1.0))).toVar();
  const grain = fbm01(fbm4((p).mul(float(13.0)), (P).mul(float(13.0)), float(0.5))).toVar();
  c.mulAssign((float(0.965)).add((float(0.07)).mul(grain)));
  rough.assign(((((float(0.82)).add((float(0.05)).mul(grain))).add(((float(1.0)).sub(clamp((sA).add(sB), float(0.0), float(1.0)))).mul(float(0.06)))).sub((sA).mul((float(0.06)).add((float(0.07)).mul(a.z))))).sub(((sB).mul(float(0.05))).mul(b.z)));
  metal.assign(float(0.0));
  ao.assign(mix(float(0.87), float(1.0), smoothstep(float(0.42), float(0.66), h)));
  const dust = (float(1.0)).sub(smoothstep(float(0.44), float(0.62), h)).toVar();
  c.assign(mix(c, (cBed).mul(float(1.04)), (dust).mul(float(0.5))));
  rough.addAssign((dust).mul(float(0.08)));
  ao.assign(mix(ao, float(1.0), (dust).mul(float(0.3))));
  const drift = fbm01(fbm4(domainWarp(((p).mul(float(0.9))).add(float(17.0)), (P).mul(float(0.9)), float(0.8), 3), (P).mul(float(0.9)), float(0.6))).toVar();
  h.addAssign(((drift).sub(float(0.5))).mul(float(0.10)));
  c.mulAssign((float(0.86)).add((float(0.28)).mul(drift)));
  rough.addAssign(((drift).sub(float(0.5))).mul(float(0.10)));
  c.assign(mix(c, (cBed).mul((float(0.92)).add((float(0.22)).mul(drift))), (smoothstep(float(0.55), float(0.88), drift)).mul(float(0.72))));
  const scuff = fbm01(fbm4(shear((p).mul(float(2.2)), float(0.0), float(6.0)), shearPeriod((P).mul(float(2.2)), float(6.0)), float(0.5))).toVar();
  c.mulAssign((float(1.0)).sub((smoothstep(float(0.55), float(0.92), scuff)).mul(float(0.10))));
  rough.subAssign((smoothstep(float(0.6), float(0.95), scuff)).mul(float(0.08)));
  alb.assign(clamp(c, vec3(float(0.02)), vec3(float(0.78))));
  rough.assign(clamp(rough, float(0.62), float(0.99)));
  ao.assign(clamp(ao, float(0.72), float(1.0)));
  h.assign(clamp(h, float(0.0), float(1.0)));
  return Surface(alb, h, rough, metal, ao);
});

