import { Fn, abs, clamp, float, floor, fract, length, max, mix, pow, sign, sin, smoothstep, step, vec2, vec3 } from 'three/tsl';
import { authoredColor } from '../color-tsl.js';
import { Surface } from './surface.js';
import { billow5, fbm01, fbm3, fbm4, fbm5, hash11, hash12, scratches, shear, shearPeriod, warp as domainWarp, worley } from '../noise-tsl.js';
import { rustColor } from './rust-color.js';

// METAL_RUST: authored channel stack migrated from surfaces-metal.js.
export const metalRustSurface = Fn(([coords, seed]) => {
  const alb = vec3(0.5).toVar(), h = float(0.5).toVar();
  const rough = float(0.5).toVar(), metal = float(0).toVar(), ao = float(1).toVar();
  const P = vec2(float(8.0)).toVar();
  const p = ((coords).mul(P)).add((seed).mul(float(7.7))).toVar();
  const mill = fbm01(fbm4(shear((p).mul(float(4.0)), float(1.0), float(6.0)), shearPeriod((P).mul(float(4.0)), float(6.0)), float(0.5))).toVar();
  const fine = fbm01(fbm4((p).mul(float(22.0)), (P).mul(float(22.0)), float(0.5))).toVar();
  const steel = (authoredColor(0.330, 0.335, 0.345)).mul((float(0.90)).add((float(0.18)).mul(mill))).toVar();
  const c = steel.toVar();
  h.assign(((float(0.72)).add(((mill).sub(float(0.5))).mul(float(0.02)))).add(((fine).sub(float(0.5))).mul(float(0.01))));
  rough.assign(((float(0.40)).add(((mill).sub(float(0.5))).mul(float(0.16)))).add(((fine).sub(float(0.5))).mul(float(0.08))));
  metal.assign(float(1.0));
  ao.assign(float(1.0));
  const wp = domainWarp((p).mul(float(1.4)), (P).mul(float(1.4)), float(1.2), 4).toVar();
  const bloom = billow5(wp, (P).mul(float(1.4)), float(0.6)).toVar();
  bloom.assign((float(1.0)).sub(bloom));
  const spread = fbm01(fbm3(((p).mul(float(0.7))).add(float(12.0)), (P).mul(float(0.7)), float(0.6))).toVar();
  const rust = smoothstep(float(0.36), float(0.72), (bloom).mul((float(0.55)).add((float(0.85)).mul(spread)))).toVar();
  const rustGrain = fbm01(fbm4((p).mul(float(26.0)), (P).mul(float(26.0)), float(0.55))).toVar();
  const pit = fbm01(fbm3((p).mul(float(24.0)), (P).mul(float(24.0)), float(0.5))).toVar();
  const scale = worley((p).mul(float(16.0)), (P).mul(float(16.0)), float(1.0)).x.toVar();
  const flake = ((smoothstep(float(0.10), float(0.30), scale).oneMinus()).mul(smoothstep(float(0.25), float(0.55), rust))).mul((float(1.0)).sub(smoothstep(float(0.8), float(1.0), rust))).toVar();
  const rustAge = fbm01(fbm4(((p).mul(float(0.85))).add(float(21.0)), (P).mul(float(0.85)), float(0.62))).toVar();
  const rustCol = rustColor(((rustAge).mul(float(0.8))).add((rust).mul(float(0.3))), rustGrain).toVar();
  c.assign(mix(c, rustCol, rust));
  metal.assign(mix(float(1.0), float(0.0), smoothstep(float(0.15), float(0.55), rust)));
  rough.assign(mix(rough, (float(0.86)).add((float(0.10)).mul(rustGrain)), smoothstep(float(0.1), float(0.6), rust)));
  h.addAssign((((rust).mul(float(0.11))).mul((float(0.4)).add(rustGrain))).add((flake).mul(float(0.13))));
  h.subAssign(((smoothstep(float(0.5), float(0.95), rust)).mul(pit)).mul(float(0.14)));
  ao.subAssign(((flake).mul(float(0.30))).add((smoothstep(float(0.6), float(1.0), rust)).mul(float(0.15))));
  const pits = worley((p).mul(float(22.0)), (P).mul(float(22.0)), float(1.0)).toVar();
  const deep = ((smoothstep(float(0.0), float(0.22), pits.x).oneMinus()).mul(step(float(0.72), pits.w))).mul(smoothstep(float(0.3), float(0.8), rust)).toVar();
  h.subAssign((deep).mul(float(0.22)));
  ao.subAssign((deep).mul(float(0.45)));
  c.assign(mix(c, (rustCol).mul(float(0.35)), (deep).mul(float(0.7))));
  const scr = scratches((p).mul(float(3.0)), (P).mul(float(3.0)), float(12.0), float(1.0), float(0.60)).toVar();
  scr.addAssign((scratches(((p).mul(float(5.0))).add(float(8.0)), (P).mul(float(5.0)), float(9.0), (float(2.0)).negate(), float(0.66))).mul(float(0.7)));
  scr.assign((clamp(scr, float(0.0), float(1.0))).mul(float(0.6)));
  c.assign(mix(c, authoredColor(0.480, 0.485, 0.495), (scr).mul(float(0.8))));
  metal.assign(mix(metal, float(1.0), (scr).mul(float(0.85))));
  rough.assign(mix(rough, float(0.24), (scr).mul(float(0.7))));
  h.subAssign((scr).mul(float(0.010)));
  const grime = smoothstep(float(0.55), float(0.9), fbm01(fbm5(vec2((p.x).mul(float(5.0)), (p.y).mul(float(0.8))), vec2((P.x).mul(float(5.0)), max(P.y, float(1.0))), float(0.55)))).toVar();
  c.mulAssign((float(1.0)).sub((grime).mul(float(0.25))));
  rough.addAssign((grime).mul(float(0.08)));
  alb.assign(clamp(c, vec3(float(0.02)), vec3(float(0.80))));
  rough.assign(clamp(rough, float(0.12), float(0.99)));
  ao.assign(clamp(ao, float(0.15), float(1.0)));
  h.assign(clamp(h, float(0.0), float(1.0)));
  return Surface(alb, h, rough, metal, ao);
});

// METAL_PAINTED: authored channel stack migrated from surfaces-metal.js.
export const metalPaintedSurface = Fn(([coords, seed, tintA, , param]) => {
  const alb = vec3(0.5).toVar(), h = float(0.5).toVar();
  const rough = float(0.5).toVar(), metal = float(0).toVar(), ao = float(1).toVar();
  const P = vec2(float(8.0)).toVar();
  const p = ((coords).mul(P)).add((seed).mul(float(11.3))).toVar();
  const mill = fbm01(fbm4(shear((p).mul(float(5.0)), float(1.0), float(8.0)), shearPeriod((P).mul(float(5.0)), float(8.0)), float(0.5))).toVar();
  const steel = (authoredColor(0.330, 0.335, 0.345)).mul((float(0.88)).add((float(0.2)).mul(mill))).toVar();
  const bloom = (float(1.0)).sub(billow5(domainWarp((p).mul(float(1.8)), (P).mul(float(1.8)), float(1.1), 4), (P).mul(float(1.8)), float(0.6))).toVar();
  const rustField = smoothstep(float(0.60), float(0.92), bloom).toVar();
  const rustGrain = fbm01(fbm4((p).mul(float(22.0)), (P).mul(float(22.0)), float(0.55))).toVar();
  const rustCol = rustColor(rustField, rustGrain).toVar();
  const peel = fbm01(fbm4((p).mul(float(22.0)), (P).mul(float(22.0)), float(0.5))).toVar();
  const roller = fbm01(fbm4(shear((p).mul(float(2.0)), float(0.0), float(3.0)), shearPeriod((P).mul(float(2.0)), float(3.0)), float(0.5))).toVar();
  const paint = (tintA).mul((float(0.90)).add((float(0.16)).mul(roller))).toVar();
  paint.mulAssign((float(0.96)).add((float(0.08)).mul(peel)));
  const bleach = smoothstep(float(0.35), float(0.85), fbm01(fbm3((p).mul(float(0.8)), (P).mul(float(0.8)), float(0.6)))).toVar();
  paint.assign(mix(paint, ((paint).mul(float(1.25))).add(float(0.03)), (bleach).mul(float(0.5))));
  const chipField = fbm01(fbm5(domainWarp(((p).mul(float(2.6))).add(float(4.0)), (P).mul(float(2.6)), float(0.9), 3), (P).mul(float(2.6)), float(0.55))).toVar();
  const chipEdge = fbm01(fbm4((p).mul(float(12.0)), (P).mul(float(12.0)), float(0.5))).toVar();
  const chipSrc = ((((chipField).mul(float(0.60))).add((chipEdge).mul(float(0.20)))).add((rustField).mul(float(0.32)))).add((param.z).mul(float(0.25))).toVar();
  const chip = smoothstep(float(0.66), float(0.92), chipSrc).toVar();
  const dings = worley((p).mul(float(20.0)), (P).mul(float(20.0)), float(1.0)).toVar();
  const ding = (smoothstep(float(0.03), float(0.14), dings.x).oneMinus()).mul(step(float(0.88), dings.w)).toVar();
  chip.assign(clamp((chip).add(ding), float(0.0), float(1.0)));
  const scr = scratches((p).mul(float(2.5)), (P).mul(float(2.5)), float(14.0), float(1.0), float(0.62)).toVar();
  scr.addAssign((scratches(((p).mul(float(4.0))).add(float(21.0)), (P).mul(float(4.0)), float(10.0), (float(1.0)).negate(), float(0.66))).mul(float(0.8)));
  scr.assign(clamp(scr, float(0.0), float(1.0)));
  const primer = authoredColor(0.470, 0.300, 0.180).toVar();
  const primerBand = (smoothstep(float(0.0), float(0.35), chip)).mul((float(1.0)).sub(smoothstep(float(0.35), float(0.6), chip))).toVar();
  const c = paint.toVar();
  const r = ((float(0.42)).add(((peel).sub(float(0.5))).mul(float(0.22)))).add((bleach).mul(float(0.16))).toVar();
  const mtl = float(0.0).toVar();
  h.assign(((float(0.74)).add(((roller).sub(float(0.5))).mul(float(0.02)))).add(((peel).sub(float(0.5))).mul(float(0.012))));
  ao.assign(float(1.0));
  c.assign(mix(c, primer, (primerBand).mul(float(0.7))));
  c.assign(mix(c, rustCol, (smoothstep(float(0.35), float(0.75), chip)).mul((float(0.55)).add((float(0.45)).mul(rustField)))));
  c.assign(mix(c, steel, ((smoothstep(float(0.75), float(0.95), chip)).mul((float(1.0)).sub(rustField))).mul(float(0.9))));
  r.assign(mix(r, float(0.88), (smoothstep(float(0.3), float(0.8), chip)).mul((float(0.4)).add((float(0.6)).mul(rustField)))));
  r.assign(mix(r, float(0.38), (smoothstep(float(0.8), float(1.0), chip)).mul((float(1.0)).sub(rustField))));
  mtl.assign(mix(float(0.0), float(1.0), (smoothstep(float(0.78), float(0.96), chip)).mul((float(1.0)).sub(smoothstep(float(0.2), float(0.7), rustField)))));
  h.subAssign((smoothstep(float(0.4), float(0.8), chip)).mul(float(0.16)));
  ao.subAssign((smoothstep(float(0.35), float(0.7), chip)).mul(float(0.22)));
  const lip = (smoothstep(float(0.30), float(0.42), chip)).mul((float(1.0)).sub(smoothstep(float(0.42), float(0.55), chip))).toVar();
  c.mulAssign((float(1.0)).add((lip).mul(float(0.15))));
  h.addAssign((lip).mul(float(0.05)));
  c.assign(mix(c, authoredColor(0.500, 0.505, 0.515), (scr).mul(float(0.55))));
  mtl.assign(mix(mtl, float(1.0), (scr).mul(float(0.6))));
  r.assign(mix(r, float(0.26), (scr).mul(float(0.55))));
  const streak = fbm01(fbm5(vec2((p.x).mul(float(6.0)), (p.y).mul(float(0.7))), vec2((P.x).mul(float(6.0)), max(P.y, float(1.0))), float(0.55))).toVar();
  const grime = smoothstep(float(0.52), float(0.92), streak).toVar();
  c.mulAssign((float(1.0)).sub((grime).mul(float(0.30))));
  r.addAssign((grime).mul(float(0.10)));
  mtl.mulAssign((float(1.0)).sub((grime).mul(float(0.5))));
  const bleed = (smoothstep(float(0.66), float(0.95), streak)).mul(smoothstep(float(0.2), float(0.6), rustField)).toVar();
  c.assign(mix(c, authoredColor(0.360, 0.190, 0.090), (bleed).mul(float(0.45))));
  const cavity = (float(1.0)).sub(smoothstep(float(0.62), float(0.78), h)).toVar();
  c.mulAssign((float(1.0)).sub((cavity).mul(float(0.18))));
  alb.assign(clamp(c, vec3(float(0.02)), vec3(float(0.85))));
  rough.assign(clamp(r, float(0.14), float(0.99)));
  metal.assign(clamp(mtl, float(0.0), float(1.0)));
  ao.assign(clamp(ao, float(0.2), float(1.0)));
  h.assign(clamp(h, float(0.0), float(1.0)));
  return Surface(alb, h, rough, metal, ao);
});

// CORRUGATED: authored channel stack migrated from surfaces-metal.js.
export const corrugatedSurface = Fn(([coords, seed]) => {
  const alb = vec3(0.5).toVar(), h = float(0.5).toVar();
  const rough = float(0.5).toVar(), metal = float(0).toVar(), ao = float(1).toVar();
  const P = vec2(float(8.0)).toVar();
  const RIDGES = float(12.0).toVar();
  const p = ((coords).mul(P)).add((seed).mul(float(6.1))).toVar();
  const t = ((coords.x).mul(RIDGES)).mul(float(6.28318530718)).toVar();
  const wave = sin(t).toVar();
  const profile = (((sign(wave)).mul(pow(abs(wave), float(0.72)))).mul(float(0.5))).add(float(0.5)).toVar();
  const panel = ((coords.x).mul(RIDGES)).div(float(4.0)).toVar();
  const panelId = floor(panel).toVar();
  const lap = (smoothstep(float(0.0), float(0.06), fract(panel))).mul(smoothstep(float(0.0), float(0.06), (float(1.0)).sub(fract(panel)))).toVar();
  const panelStep = ((hash11((panelId).add(seed))).sub(float(0.5))).mul(float(0.05)).toVar();
  const dents = fbm01(fbm4((p).mul(float(2.2)), (P).mul(float(2.2)), float(0.6))).toVar();
  const fine = fbm01(fbm4((p).mul(float(11.0)), (P).mul(float(11.0)), float(0.5))).toVar();
  h.assign(((((float(0.18)).add((profile).mul(float(0.62)))).add(panelStep)).add(((dents).sub(float(0.5))).mul(float(0.07)))).add(((fine).sub(float(0.5))).mul(float(0.012))));
  h.subAssign(((float(1.0)).sub(lap)).mul(float(0.06)));
  const sp = worley((p).mul(float(7.0)), (P).mul(float(7.0)), float(1.0)).toVar();
  const spangle = smoothstep(float(0.05), float(0.55), sp.x).oneMinus().toVar();
  const zinc = authoredColor(0.520, 0.535, 0.545).toVar();
  const c = mix((zinc).mul(float(0.86)), (zinc).mul(float(1.12)), (spangle).mul((float(0.3)).add((float(0.7)).mul(sp.z)))).toVar();
  c.mulAssign((float(0.94)).add((float(0.12)).mul(fine)));
  metal.assign(float(1.0));
  rough.assign(((float(0.34)).add(((float(1.0)).sub(spangle)).mul(float(0.16)))).add(((fine).sub(float(0.5))).mul(float(0.08))));
  ao.assign(float(1.0));
  const valley = (float(1.0)).sub(profile).toVar();
  const rustField = smoothstep(float(0.62), float(0.98), (((float(1.0)).sub(billow5(domainWarp((p).mul(float(1.6)), (P).mul(float(1.6)), float(1.0), 4), (P).mul(float(1.6)), float(0.6)))).mul((float(0.58)).add((float(0.40)).mul(valley)))).add(((float(1.0)).sub(coords.y)).mul(float(0.16)))).toVar();
  const rustGrain = fbm01(fbm4((p).mul(float(22.0)), (P).mul(float(22.0)), float(0.55))).toVar();
  const rustCol = rustColor(rustField, rustGrain).toVar();
  c.assign(mix(c, rustCol, rustField));
  metal.assign(mix(metal, float(0.0), smoothstep(float(0.15), float(0.6), rustField)));
  rough.assign(mix(rough, (float(0.88)).add((float(0.08)).mul(rustGrain)), smoothstep(float(0.1), float(0.6), rustField)));
  h.addAssign(((rustField).mul(float(0.02))).mul(rustGrain));
  const hole = worley(((p).mul(float(5.0))).add(float(31.0)), (P).mul(float(5.0)), float(0.95)).toVar();
  const perf = ((smoothstep(float(0.02), float(0.10), hole.x).oneMinus()).mul(step(float(0.94), hole.w))).mul(smoothstep(float(0.5), float(0.9), rustField)).toVar();
  h.subAssign((perf).mul(float(0.5)));
  ao.subAssign((perf).mul(float(0.7)));
  c.assign(mix(c, (rustCol).mul(float(0.25)), perf));
  const crown = smoothstep(float(0.72), float(0.95), profile).toVar();
  const fx = vec2((fract((coords.x).mul(RIDGES))).sub(float(0.5)), (fract((coords.y).mul(float(3.0)))).sub(float(0.5))).toVar();
  const fd = length((fx).mul(vec2(float(1.0), (RIDGES).div(float(3.0))))).toVar();
  const screwRnd = hash12((floor(vec2((coords.x).mul(RIDGES), (coords.y).mul(float(3.0))))).add(seed)).toVar();
  const screw = ((smoothstep(float(0.11), float(0.16), fd).oneMinus()).mul(crown)).mul(step(float(0.25), screwRnd)).toVar();
  const washer = ((smoothstep(float(0.18), float(0.24), fd).oneMinus()).mul(crown)).mul(step(float(0.25), screwRnd)).toVar();
  h.addAssign(((washer).mul(float(0.02))).add((screw).mul(float(0.035))));
  c.assign(mix(c, authoredColor(0.120, 0.115, 0.110), (washer).mul(float(0.8))));
  c.assign(mix(c, mix(authoredColor(0.400, 0.405, 0.410), rustCol, rustField), screw));
  rough.assign(mix(rough, float(0.85), (washer).mul(float(0.8))));
  rough.assign(mix(rough, (float(0.42)).add((rustField).mul(float(0.4))), screw));
  metal.assign(mix(metal, float(0.0), (washer).mul(float(0.9))));
  metal.assign(mix(metal, (float(1.0)).sub(rustField), screw));
  ao.subAssign(((washer).sub(screw)).mul(float(0.35)));
  const weep = ((washer).mul(float(0.0))).add((((smoothstep(float(0.20), float(0.34), fd).oneMinus()).mul(step(float(0.25), screwRnd))).mul(crown)).mul(smoothstep(float(0.0), float(0.5), (fract((coords.y).mul(float(3.0)))).sub(float(0.5))))).toVar();
  c.assign(mix(c, authoredColor(0.330, 0.170, 0.080), (clamp(weep, float(0.0), float(1.0))).mul(float(0.5))));
  const dirt = (valley).mul(smoothstep(float(0.35), float(0.8), fbm01(fbm4((p).mul(float(3.0)), (P).mul(float(3.0)), float(0.55))))).toVar();
  c.assign(mix(c, authoredColor(0.200, 0.185, 0.160), (dirt).mul(float(0.40))));
  rough.addAssign((dirt).mul(float(0.14)));
  metal.mulAssign((float(1.0)).sub((dirt).mul(float(0.5))));
  ao.subAssign((valley).mul(float(0.18)));
  alb.assign(clamp(c, vec3(float(0.02)), vec3(float(0.85))));
  rough.assign(clamp(rough, float(0.14), float(0.99)));
  metal.assign(clamp(metal, float(0.0), float(1.0)));
  ao.assign(clamp(ao, float(0.15), float(1.0)));
  h.assign(clamp(h, float(0.0), float(1.0)));
  return Surface(alb, h, rough, metal, ao);
});

