import { Fn, abs, clamp, cos, exp, float, floor, fract, length, max, min, mix, mod, smoothstep, step, vec2, vec3 } from 'three/tsl';
import { authoredColor } from '../color-tsl.js';
import { Surface } from './surface.js';
import { fbm01, fbm3, fbm4, fbm5, hash11, hash12, hash42, scratches, shear, shearPeriod, warp as domainWarp } from '../noise-tsl.js';

// WOOD: authored channel stack migrated from surfaces-organic.js.
export const woodSurface = Fn(([coords, seed]) => {
  const alb = vec3(0.5).toVar(), h = float(0.5).toVar();
  const rough = float(0.5).toVar(), metal = float(0).toVar(), ao = float(1).toVar();
  const P = vec2(float(8.0)).toVar();
  const PLANKS = float(5.0).toVar();
  const p = ((coords).mul(P)).add((seed).mul(float(12.9))).toVar();
  const rowF = (coords.y).mul(PLANKS).toVar();
  const row = floor(rowF).toVar();
  const rf = fract(rowF).toVar();
  const stagger = hash11((row).add((seed).mul(float(2.0)))).toVar();
  const lenF = ((coords.x).mul(float(2.0))).add(stagger).toVar();
  const board = floor(lenF).toVar();
  const lf = fract(lenF).toVar();
  const rnd = hash42((vec2(board, row)).add(seed)).toVar();
  const GY = float(0.035).toVar();
  const GX = float(0.010).toVar();
  const ey = min(smoothstep(float(0.0), GY, rf), smoothstep(float(0.0), GY, (float(1.0)).sub(rf))).toVar();
  const ex = min(smoothstep(float(0.0), GX, lf), smoothstep(float(0.0), GX, (float(1.0)).sub(lf))).toVar();
  const face = min(ex, ey).toVar();
  const gp = vec2(((lf).mul(float(2.0))).add((rnd.x).mul(float(13.0))), (rf).add((rnd.y).mul(float(7.0)))).toVar();
  const GP = vec2(float(16.0), float(8.0)).toVar();
  const warp = fbm4(vec2((gp.x).mul(float(3.0)), (gp.y).mul(float(12.0))), vec2((GP.x).mul(float(3.0)), (GP.y).mul(float(12.0))), float(0.55)).toVar();
  const ringCoord = (((gp.y).mul((float(14.0)).add((rnd.z).mul(float(12.0))))).add((warp).mul(float(2.2)))).add((rnd.w).mul(float(5.0))).toVar();
  const knotP = vec2((float(0.25)).add((rnd.x).mul(float(0.5))), (float(0.35)).add((rnd.y).mul(float(0.3)))).toVar();
  const kd = length(((vec2(lf, rf)).sub(knotP)).mul(vec2(float(2.2), float(1.0)))).toVar();
  const hasKnot = step(float(0.68), rnd.z).toVar();
  const knotPull = (hasKnot).mul(exp(((kd).negate()).mul(float(9.0)))).toVar();
  ringCoord.assign(mix(ringCoord, (kd).mul(float(42.0)), clamp((knotPull).mul(float(1.6)), float(0.0), float(1.0))));
  const rings = fract(ringCoord).toVar();
  const ringDark = (smoothstep(float(0.42), float(0.5), rings)).mul((float(1.0)).sub(smoothstep(float(0.5), float(0.62), rings))).toVar();
  const latewood = smoothstep(float(0.30), float(0.52), rings).toVar();
  const fibre = fbm01(fbm4(shear((p).mul(float(6.0)), float(0.0), float(40.0)), shearPeriod((P).mul(float(6.0)), float(40.0)), float(0.5))).toVar();
  const micro = fbm01(fbm3((p).mul(float(22.0)), (P).mul(float(22.0)), float(0.5))).toVar();
  const wLight = authoredColor(0.505, 0.408, 0.290).toVar();
  const wMid = authoredColor(0.362, 0.272, 0.180).toVar();
  const wDark = authoredColor(0.205, 0.142, 0.092).toVar();
  const wGrey = authoredColor(0.372, 0.355, 0.328).toVar();
  const c = mix(wLight, wMid, ((rnd.w).mul(float(0.8))).add((latewood).mul(float(0.5)))).toVar();
  c.assign(mix(c, wDark, (ringDark).mul(float(0.65))));
  c.mulAssign((float(0.90)).add((float(0.18)).mul(fibre)));
  c.assign(mix(c, (wDark).mul(float(0.7)), (clamp((knotPull).mul(float(2.2)), float(0.0), float(1.0))).mul(float(0.8))));
  const weather = (smoothstep(float(0.20), float(0.85), fbm01(fbm3((p).mul(float(0.8)), (P).mul(float(0.8)), float(0.6))))).mul((float(0.4)).add((float(0.6)).mul(rnd.x))).toVar();
  c.assign(mix(c, wGrey, (weather).mul(float(0.68))));
  const faceH = ((((float(0.74)).sub((ringDark).mul(float(0.02)))).sub((latewood).mul(float(0.012)))).add(((fibre).sub(float(0.5))).mul(float(0.03)))).add(((micro).sub(float(0.5))).mul(float(0.008))).toVar();
  faceH.addAssign(((rnd.y).sub(float(0.5))).mul(float(0.035)));
  faceH.subAssign((clamp((knotPull).mul(float(1.5)), float(0.0), float(1.0))).mul(float(0.03)));
  const split = (scratches((vec2(p.x, p.y)).mul(float(2.0)), (P).mul(float(2.0)), float(30.0), float(0.0), float(0.66))).mul(weather).toVar();
  faceH.subAssign((split).mul(float(0.10)));
  c.assign(mix(c, (wDark).mul(float(0.45)), (split).mul(float(0.7))));
  const saw = fbm01(fbm3((shear((p).mul(float(3.0)), float(0.0), float(1.0))).mul(vec2(float(30.0), float(1.0))), vec2((P.x).mul(float(90.0)), (P.y).mul(float(3.0))), float(0.5))).toVar();
  faceH.addAssign(((saw).sub(float(0.5))).mul(float(0.012)));
  const edgeD = min((min(rf, (float(1.0)).sub(rf))).div(GY), (min(lf, (float(1.0)).sub(lf))).div(GX)).toVar();
  const bevel = (float(1.0)).sub(smoothstep(float(0.0), float(2.4), edgeD)).toVar();
  faceH.subAssign((bevel).mul(float(0.035)));
  c.mulAssign((float(1.0)).sub((bevel).mul(float(0.10))));
  c.assign(mix(c, (wLight).mul(float(1.15)), ((bevel).mul(smoothstep(float(0.5), float(0.9), fbm01(fbm3((p).mul(float(20.0)), (P).mul(float(20.0)), float(0.5)))))).mul(float(0.35))));
  const m = smoothstep(float(0.05), float(0.7), face).toVar();
  h.assign(mix(float(0.44), faceH, m));
  c.assign(mix((wDark).mul(float(0.25)), c, m));
  rough.assign(mix(float(0.95), (((float(0.62)).add((float(0.22)).mul(fibre))).add((weather).mul(float(0.20)))).add((split).mul(float(0.15))), m));
  ao.assign((mix(float(0.25), float(1.0), smoothstep(float(0.0), float(0.5), face))).sub(((bevel).mul(float(0.12))).mul(m)));
  metal.assign(float(0.0));
  const nf = vec2((fract(((lf).mul(float(3.0))).add(float(0.5)))).sub(float(0.5)), (rf).sub(float(0.5))).toVar();
  const nd = length((((nf).mul(vec2(float(3.0), float(1.0)))).div(vec2(float(3.0), float(1.0)))).mul(vec2(float(1.0), float(1.0)))).toVar();
  nd.assign(length((vec2((fract(((lf).mul(float(3.0))).add(float(0.5)))).sub(float(0.5)), (rf).sub(float(0.22)))).mul(vec2(float(1.4), float(1.0)))));
  const nail = ((smoothstep(float(0.030), float(0.055), nd).oneMinus()).mul(m)).mul(step(float(0.3), rnd.w)).toVar();
  h.subAssign((nail).mul(float(0.02)));
  c.assign(mix(c, authoredColor(0.230, 0.200, 0.170), (nail).mul(float(0.85))));
  rough.assign(mix(rough, float(0.55), nail));
  metal.assign(mix(metal, float(0.85), (nail).mul(float(0.7))));
  ao.subAssign((nail).mul(float(0.25)));
  const weep = (((smoothstep(float(0.05), float(0.11), nd).oneMinus()).mul(step(float(0.3), rnd.w))).mul(smoothstep(float(0.0), float(0.6), (rf).sub(float(0.22))))).mul(m).toVar();
  c.assign(mix(c, authoredColor(0.330, 0.185, 0.095), (clamp(weep, float(0.0), float(1.0))).mul(float(0.4))));
  const cavity = (float(1.0)).sub(smoothstep(float(0.55), float(0.78), h)).toVar();
  c.assign(mix(c, authoredColor(0.120, 0.106, 0.088), (cavity).mul(float(0.45))));
  const soil = smoothstep(float(0.40), float(0.88), fbm01(fbm5(domainWarp(((p).mul(float(2.2))).add(float(5.0)), (P).mul(float(2.2)), float(0.9), 3), (P).mul(float(2.2)), float(0.6)))).toVar();
  c.assign(mix(c, authoredColor(0.185, 0.160, 0.128), (soil).mul(float(0.40))));
  rough.addAssign((soil).mul(float(0.08)));
  alb.assign(clamp(c, vec3(float(0.02)), vec3(float(0.80))));
  rough.assign(clamp(rough, float(0.25), float(0.99)));
  ao.assign(clamp(ao, float(0.12), float(1.0)));
  h.assign(clamp(h, float(0.0), float(1.0)));
  return Surface(alb, h, rough, metal, ao);
});

// FABRIC: authored channel stack migrated from surfaces-organic.js.
export const fabricSurface = Fn(([coords, seed, tintA, tintB]) => {
  const alb = vec3(0.5).toVar(), h = float(0.5).toVar();
  const rough = float(0.5).toVar(), metal = float(0).toVar(), ao = float(1).toVar();
  const P = vec2(float(8.0)).toVar();
  const THREADS = float(96.0).toVar();
  const p = ((coords).mul(P)).add((seed).mul(float(3.9))).toVar();
  const t = (coords).mul(THREADS).toVar();
  const cell = floor(t).toVar();
  const f = (fract(t)).sub(float(0.5)).toVar();
  const over = mod((cell.x).add(cell.y), float(2.0)).toVar();
  const warpProfile = cos((f.x).mul(float(3.14159))).toVar();
  const weftProfile = cos((f.y).mul(float(3.14159))).toVar();
  const top = mix(warpProfile, weftProfile, over).toVar();
  const bot = (mix(weftProfile, warpProfile, over)).mul(float(0.45)).toVar();
  const weave = max(top, bot).toVar();
  const threadId = hash12((cell).add(seed)).toVar();
  const fuzz = fbm01(fbm3((p).mul(float(12.0)), (P).mul(float(12.0)), float(0.55))).toVar();
  const slub = fbm01(fbm4((p).mul(float(14.0)), (P).mul(float(14.0)), float(0.5))).toVar();
  const macro = fbm01(fbm4((p).mul(float(1.2)), (P).mul(float(1.2)), float(0.6))).toVar();
  const cA = tintA.toVar();
  const cB = tintB.toVar();
  const c = mix(cA, cB, ((threadId).mul(float(0.6))).add((slub).mul(float(0.4)))).toVar();
  c.mulAssign((float(0.865)).add((float(0.215)).mul(((weave).mul(float(0.5))).add(float(0.5)))));
  c.mulAssign((float(0.960)).add((float(0.075)).mul(fuzz)));
  c.mulAssign((float(0.90)).add((float(0.20)).mul(macro)));
  h.assign((((float(0.55)).add((weave).mul(float(0.30)))).add(((fuzz).sub(float(0.5))).mul(float(0.03)))).add(((slub).sub(float(0.5))).mul(float(0.05))));
  rough.assign(((float(0.86)).add(((float(1.0)).sub(weave)).mul(float(0.08)))).add(((fuzz).sub(float(0.5))).mul(float(0.06))));
  metal.assign(float(0.0));
  ao.assign(mix(float(0.82), float(1.0), smoothstep((float(0.4)).negate(), float(0.9), weave)));
  const foldC = (((coords.y).mul(float(2.6))).add((coords.x).mul(float(0.55)))).add((fbm01(fbm3((p).mul(float(0.9)), (P).mul(float(0.9)), float(0.62)))).mul(float(2.2))).toVar();
  const foldT = (abs((fract(foldC)).sub(float(0.5)))).mul(float(2.0)).toVar();
  const crest = (float(1.0)).sub(foldT).toVar();
  const foldR = hash11(((floor(foldC)).mul(float(2.13))).add(seed)).toVar();
  const fold = ((crest).mul(crest)).mul((float(0.55)).add((float(0.75)).mul(foldR))).toVar();
  h.addAssign(((fold).sub(float(0.30))).mul(float(0.115)));
  c.mulAssign((float(0.895)).add((float(0.21)).mul(fold)));
  ao.subAssign(((float(1.0)).sub(crest)).mul(float(0.14)));
  const creaseLine = (float(1.0)).sub(smoothstep(float(0.0), float(0.10), foldT)).toVar();
  rough.subAssign((creaseLine).mul(float(0.06)));
  c.mulAssign((float(1.0)).add((creaseLine).mul(float(0.05))));
  const wearField = smoothstep(float(0.58), float(0.82), fbm01(fbm4(domainWarp((p).mul(float(2.0)), (P).mul(float(2.0)), float(0.8), 3), (P).mul(float(2.0)), float(0.55)))).toVar();
  c.assign(mix(c, ((c).mul(float(1.35))).add(float(0.02)), (wearField).mul(float(0.5))));
  rough.addAssign((wearField).mul(float(0.06)));
  h.subAssign((wearField).mul(float(0.05)));
  const pulled = scratches((p).mul(float(3.0)), (P).mul(float(3.0)), float(18.0), float(1.0), float(0.68)).toVar();
  h.addAssign((pulled).mul(float(0.05)));
  c.mulAssign((float(1.0)).sub((pulled).mul(float(0.10))));
  const stain = smoothstep(float(0.55), float(0.9), fbm01(fbm5(domainWarp(((p).mul(float(1.5))).add(float(7.0)), (P).mul(float(1.5)), float(1.0), 3), (P).mul(float(1.5)), float(0.6)))).toVar();
  c.assign(mix(c, ((c).mul(float(0.42))).add(authoredColor(0.09, 0.08, 0.06)), (stain).mul(float(0.55))));
  rough.addAssign((stain).mul(float(0.05)));
  const dust = smoothstep(float(0.4), float(0.85), fbm01(fbm4((p).mul(float(6.0)), (P).mul(float(6.0)), float(0.5)))).toVar();
  c.assign(mix(c, authoredColor(0.400, 0.375, 0.335), (dust).mul(float(0.14))));
  alb.assign(clamp(c, vec3(float(0.02)), vec3(float(0.85))));
  rough.assign(clamp(rough, float(0.5), float(0.99)));
  ao.assign(clamp(ao, float(0.25), float(1.0)));
  h.assign(clamp(h, float(0.0), float(1.0)));
  return Surface(alb, h, rough, metal, ao);
});

// BURLAP: authored channel stack migrated from surfaces-organic.js.
export const burlapSurface = Fn(([coords, seed]) => {
  const alb = vec3(0.5).toVar(), h = float(0.5).toVar();
  const rough = float(0.5).toVar(), metal = float(0).toVar(), ao = float(1).toVar();
  const P = vec2(float(8.0)).toVar();
  const THREADS = float(34.0).toVar();
  const p = ((coords).mul(P)).add((seed).mul(float(4.7))).toVar();
  const t = (coords).mul(THREADS).toVar();
  const cell = floor(t).toVar();
  const f = (fract(t)).sub(float(0.5)).toVar();
  const over = mod((cell.x).add(cell.y), float(2.0)).toVar();
  const twx = (float(0.62)).add((float(0.30)).mul(hash12((vec2(cell.x, float(0.0))).add(seed)))).toVar();
  const twy = (float(0.62)).add((float(0.30)).mul(hash12((vec2(float(0.0), cell.y)).add((seed).mul(float(1.7)))))).toVar();
  const warpP = cos((clamp((f.x).div(twx), (float(0.5)).negate(), float(0.5))).mul(float(3.14159))).toVar();
  const weftP = cos((clamp((f.y).div(twy), (float(0.5)).negate(), float(0.5))).mul(float(3.14159))).toVar();
  const top = mix(warpP, weftP, over).toVar();
  const bot = (mix(weftP, warpP, over)).mul(float(0.40)).toVar();
  const weave = max(top, bot).toVar();
  const fibre = fbm01(fbm3(shear((p).mul(float(12.0)), float(0.0), float(8.0)), shearPeriod((P).mul(float(12.0)), float(8.0)), float(0.5))).toVar();
  const macro = fbm01(fbm4((p).mul(float(1.0)), (P).mul(float(1.0)), float(0.62))).toVar();
  const dirt = fbm01(fbm5(domainWarp((p).mul(float(2.5)), (P).mul(float(2.5)), float(0.8), 3), (P).mul(float(2.5)), float(0.55))).toVar();
  const cJute = authoredColor(0.520, 0.430, 0.275).toVar();
  const cPale = authoredColor(0.640, 0.560, 0.400).toVar();
  const cSoil = authoredColor(0.230, 0.180, 0.120).toVar();
  const c = mix(cJute, cPale, ((hash12((cell).add(float(3.0)))).mul(float(0.5))).add((fibre).mul(float(0.15)))).toVar();
  c.mulAssign((float(0.855)).add((float(0.235)).mul(((weave).mul(float(0.5))).add(float(0.5)))));
  c.mulAssign((float(0.90)).add((float(0.18)).mul(macro)));
  c.assign(mix(c, cSoil, (smoothstep(float(0.42), float(0.85), dirt)).mul(float(0.60))));
  h.assign(((float(0.50)).add((weave).mul(float(0.38)))).add(((fibre).sub(float(0.5))).mul(float(0.05))));
  rough.assign((float(0.90)).add(((float(1.0)).sub(weave)).mul(float(0.06))));
  metal.assign(float(0.0));
  ao.assign(mix(float(0.74), float(1.0), smoothstep((float(0.4)).negate(), float(0.9), weave)));
  const rot = smoothstep(float(0.55), float(0.9), fbm01(fbm3(((p).mul(float(0.7))).add(float(11.0)), (P).mul(float(0.7)), float(0.6)))).toVar();
  c.assign(mix(c, (cPale).mul(float(1.15)), (rot).mul(float(0.4))));
  rough.addAssign((rot).mul(float(0.05)));
  const loose = scratches((p).mul(float(4.0)), (P).mul(float(4.0)), float(10.0), float(2.0), float(0.70)).toVar();
  h.addAssign((loose).mul(float(0.06)));
  c.assign(mix(c, cPale, (loose).mul(float(0.3))));
  const sand = (smoothstep(float(0.5), float(0.85), fbm01(fbm4((p).mul(float(12.0)), (P).mul(float(12.0)), float(0.5))))).mul((float(1.0)).sub(smoothstep(float(0.2), float(0.7), weave))).toVar();
  c.assign(mix(c, authoredColor(0.640, 0.545, 0.390), (sand).mul(float(0.45))));
  alb.assign(clamp(c, vec3(float(0.02)), vec3(float(0.80))));
  rough.assign(clamp(rough, float(0.6), float(0.99)));
  ao.assign(clamp(ao, float(0.2), float(1.0)));
  h.assign(clamp(h, float(0.0), float(1.0)));
  return Surface(alb, h, rough, metal, ao);
});

